/*


@jsonSerializable()
class MapModel {
  String? _country;
  Detail? _detail;
  double? _lat;
  double? _long;

  Autogenerated({String? country, Detail? detail, double? lat, double? long}) {
    if (country != null) {
      this._country = country;
    }
    if (detail != null) {
      this._detail = detail;
    }
    if (lat != null) {
      this._lat = lat;
    }
    if (long != null) {
      this._long = long;
    }
  }

  String? get country => _country;
  set country(String? country) => _country = country;
  Detail? get detail => _detail;
  set detail(Detail? detail) => _detail = detail;
  double? get lat => _lat;
  set lat(double? lat) => _lat = lat;
  double? get long => _long;
  set long(double? long) => _long = long;

  MapModel.fromJson(Map<String, dynamic> json) {
    _country = json['country'];
    _detail =
        json['detail'] != null ? new Detail.fromJson(json['detail']) : null;
    _lat = json['lat'];
    _long = json['long'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['country'] = this._country;
    if (this._detail != null) {
      data['detail'] = this._detail!.toJson();
    }
    data['lat'] = this._lat;
    data['long'] = this._long;
    return data;
  }
}*/
